server:
  port: 9000
  application:
    name: config-client

spring:
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8090/eureka/
